FROM ubuntu:latest

RUN apt update
RUN apt install -y \
    build-essential \
    clang \
    clang-format \
    clang-tidy \
    clangd \
    cmake \
    git \
    make \
    python3 \
    python3-pip
